### ISSUE TITLE
Detailed requirement

### ISSUE THREAD

**Issue by triinuliis7** [triinuliis7/Spordisemu#10]
At least 75% of the requirements identified and marked as in the scope of the work delivered at the end of the course are detailed in selected form (for example in use cases). Detailed requirements are in individual wiki pages/documents. Detailed requirements are accessible from the overall requirements list.

**Comment by triinuliis7** [comment]
@kelian @triinuliis7 @ingrid94

**Comment by juliakaas** [comment]
https://github.com/triinuliis7/Spordisemu/wiki/Use-case-1
https://github.com/triinuliis7/Spordisemu/wiki/Use-case-2

**Comment by triinuliis7** [comment]
This issue must be made into several issues after the use cases are done
