### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by triinuliis7** [triinuliis7/Spordisemu#13]
Release notes for the iteration are present. Reading the release notes gives an overview what features of the system are supported by the released version of the system and is thus input for the acceptance testing by the customer&course organizer. If delivered functionality contains known bugs, those issues are highlighted in release notes.

**Comment by triinuliis7** [comment]
@juliakaas @kelian @triinuliis7

**Comment by kelian** [comment]
https://github.com/triinuliis7/Spordisemu/releases/tag/v0.1
