### ISSUE TITLE
Non-functional requirements

### ISSUE THREAD

**Issue by triinuliis7** [triinuliis7/Spordisemu#2]
You have listed the most important non-functional requirements. There is at least seven measurable non-functional requirements present. You have noted the requirements down in the Wiki. Reading the requirements, I understand how you are going to measure whether the system satisfies a given requirement.

Non-functional requirement include the initial architectural choices listing what technologies you are going to use in order to complete the project.

**Comment by kelian** [comment]
Assigned to both Triinu Liis and Julia.

**Comment by kelian** [comment]
https://github.com/triinuliis7/Spordisemu/wiki/1st-iteration-(21-September)#non-functional-requirements
