### ISSUE TITLE
User can leave a rating (and a comment which is optional) to other user’s profile

### ISSUE THREAD

**Issue by triinuliis7** [triinuliis7/Spordisemu#24]

**Comment by triinuliis7** [comment]
https://github.com/triinuliis7/Spordisemu/wiki/UC7:-User-can-view-other-person's-profile.

**Comment by ingrid94** [comment]
https://github.com/triinuliis7/Spordisemu/wiki/UC9:-User-can-leave-feedback-to-other-users-profile.
