### ISSUE TITLE
User can schedule a practice

### ISSUE THREAD

**Issue by triinuliis7** [triinuliis7/Spordisemu#28]

**Comment by triinuliis7** [comment]
User can add a location, date, time, level and how many people are needed for the practice (minimum/maximum people), preferred gender.

**Comment by kelian** [comment]
https://github.com/triinuliis7/Spordisemu/wiki/UC1:-User-can-schedule-a-practice

**Comment by kelian** [comment]
Doesn't have "cancel" button and when clicking back, it doesn't show a warning of canceling a creating a practice
